# Generated by Django 4.2.2 on 2023-07-17 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sweet",
            fields=[
                ("sweet_category", models.CharField(max_length=100)),
                (
                    "sweet_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("price", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_quan", models.FloatField(default=0.0)),
                ("order_val", models.FloatField(default=0.0)),
                ("order_dt_crt", models.DateTimeField(editable=False)),
                ("order_dt_mod", models.DateTimeField()),
                ("order_id", models.IntegerField()),
                ("order_delivered", models.BooleanField(default=False)),
                ("order_confirmed", models.BooleanField(default=False)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sweet_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sweets.sweet"
                    ),
                ),
            ],
        ),
    ]
